import Head from 'next/head'
import { useCallback, useEffect, useRef, useState } from 'react'
import MapSample from '../MapSample.json'
import styles from '../public/styles/marker.module.css'
import { MainMarker } from '../components/marker/MainMarker'

export interface storeInfo {
  store_nm: string
  store_status_str: string
  ceo_no: string
  map_cood_lat: string
  map_cood_lgt: string
  marker?: any
}

export default function Home() {
  const mapRef = useRef<HTMLElement | any | null>(null)
  const markerRef = useRef<naver.maps.Marker | null>(null)
  const selectedMarker = useRef<any | null>(null)
  // const itemRef = useRef<any | null>(null)

  const [storeList, setStoreList] = useState<storeInfo[]>(MapSample.data.results)

  // 지도 띄우기
  useEffect(() => {
    mapRef.current = new naver.maps.Map('map', {
      center: new naver.maps.LatLng(37.5657, 126.9769),
      zoom: 10
    })
  }, [])

  // 마커 띄우기
  useEffect(() => {
    MapSample.data.results.map((marker: storeInfo) => {
      markerRef.current = new naver.maps.Marker({
        position: new naver.maps.LatLng(+marker.map_cood_lat, +marker.map_cood_lgt),
        map: mapRef.current,
        icon: {
          content: MainMarker(marker)
        }
      })
    })
  }, [])

  return (
    <>
      <Head>
        <title>NaverMap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.container}>
          {/* 지도 */}
          <div style={{ width: '80vw', height: '100vh' }} ref={mapRef} id="map"></div>
          {/* 매장 리스트 뿌리는 사이드바 */}
          <div className={styles.storeList}>
            {storeList.map((item) => (
              <div key={item.store_nm} className={styles.storeItem}>
                {item.store_nm}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  )
}
